insert into job_sources (
  name,
  url,
  method,
  apify_actor_id,
  api_endpoint,
  rss_url,
  cron_expression,
  is_active,
  priority
) values
  ('LinkedIn', 'https://www.linkedin.com/jobs', 'apify', 'curious_coder/linkedin-jobs-scraper', null, null, '*/30 * * * *', true, 1),
  ('Indeed', 'https://www.indeed.com', 'apify', 'misceres/indeed-scraper', null, null, '*/30 * * * *', true, 1),
  ('Glassdoor', 'https://www.glassdoor.com/Job', 'apify', 'bebity/glassdoor-jobs-scraper', null, null, '0 * * * *', true, 2),
  ('We Work Remotely', 'https://weworkremotely.com', 'rss', null, null, 'https://weworkremotely.com/remote-jobs.rss', '*/15 * * * *', true, 2),
  ('Remote.co', 'https://remote.co/remote-jobs', 'apify', null, null, null, '0 * * * *', true, 4),
  ('Wellfound', 'https://wellfound.com/jobs', 'apify', 'apify/wellfound-scraper', null, null, '0 */2 * * *', true, 3),
  ('Stack Overflow Jobs', 'https://stackoverflow.com/jobs', 'rss', null, null, 'https://stackoverflow.com/jobs/feed', '*/30 * * * *', true, 4),
  ('GitHub Jobs', 'https://github.com/features', 'apify', null, null, null, '0 */2 * * *', true, 5),
  ('Dice', 'https://www.dice.com', 'api', null, 'https://job-search-api.seigroup.com/v1/listing', null, '0 * * * *', true, 4),
  ('ZipRecruiter', 'https://www.ziprecruiter.com', 'apify', 'Brian_zhumanov/ziprecruiter-scraper', null, null, '0 * * * *', true, 3),
  ('SimplyHired', 'https://www.simplyhired.com', 'apify', 'misceres/simplyhired-scraper', null, null, '0 * * * *', true, 4),
  ('Remotive', 'https://remotive.com', 'api', null, 'https://remotive.com/api/remote-jobs', null, '*/15 * * * *', true, 2),
  ('RemoteOK', 'https://remoteok.com', 'api', null, 'https://remoteok.com/api', null, '*/15 * * * *', true, 2),
  ('Upwork', 'https://www.upwork.com', 'api', null, 'https://www.upwork.com/api', null, '0 */2 * * *', false, 5),
  ('Toptal', 'https://www.toptal.com', 'apify', null, null, null, '0 */4 * * *', false, 6),
  ('Freelancer', 'https://www.freelancer.com', 'api', null, 'https://www.freelancer.com/api', null, '0 */2 * * *', false, 5),
  ('Google Jobs', 'https://jobs.google.com', 'serpapi', null, 'https://serpapi.com/search?engine=google_jobs', null, '0 * * * *', true, 3),
  ('Adzuna', 'https://www.adzuna.com', 'api', null, 'https://api.adzuna.com/v1/api/jobs', null, '*/30 * * * *', false, 4),
  ('Jooble', 'https://jooble.org', 'api', null, 'https://jooble.org/api/', null, '0 * * * *', false, 4),
  ('Himalayas', 'https://himalayas.app/jobs', 'api', null, 'https://himalayas.app/jobs/api', null, '*/30 * * * *', true, 3),
  ('Arc.dev', 'https://arc.dev/remote-jobs', 'apify', null, null, null, '0 */4 * * *', false, 6),
  ('Authentic Jobs', 'https://authenticjobs.com', 'rss', null, null, 'https://authenticjobs.com/feed/', '0 * * * *', true, 4),
  ('CareerBuilder', 'https://www.careerbuilder.com', 'apify', 'apify/careerbuilder-scraper', null, null, '0 */2 * * *', true, 4),
  ('Monster', 'https://www.monster.com', 'api', null, null, null, '0 */2 * * *', false, 5),
  ('Rozee.pk', 'https://www.rozee.pk', 'apify', null, null, null, '0 * * * *', true, 3)
on conflict (name) do update set
  url = excluded.url,
  method = excluded.method,
  apify_actor_id = excluded.apify_actor_id,
  api_endpoint = excluded.api_endpoint,
  rss_url = excluded.rss_url,
  cron_expression = excluded.cron_expression,
  is_active = excluded.is_active,
  priority = excluded.priority;
